<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FirebirdAdmin.Presentation.Wpf\FirebirdAdmin.Presentation.Wpf.csproj" />
    <ProjectReference Include="..\FirebirdAdmin.Infrastructure\FirebirdAdmin.Infrastructure.csproj" />
    <ProjectReference Include="..\FirebirdAdmin.Application\FirebirdAdmin.Application.csproj" />
    <ProjectReference Include="..\FirebirdAdmin.Domain\FirebirdAdmin.Domain.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>
</Project>
