<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>false</PublishSingleFile>
    <PublishReadyToRun>false</PublishReadyToRun>
    <ApplicationIcon>..\FirebirdAdmin.Presentation.Wpf\Assets\Branding\FirebirdAdmin.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FirebirdAdmin.Presentation.Wpf\FirebirdAdmin.Presentation.Wpf.csproj" />
    <ProjectReference Include="..\FirebirdAdmin.Infrastructure\FirebirdAdmin.Infrastructure.csproj" />
    <ProjectReference Include="..\FirebirdAdmin.Application\FirebirdAdmin.Application.csproj" />
    <ProjectReference Include="..\FirebirdAdmin.Domain\FirebirdAdmin.Domain.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>
</Project>
