<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\FirebirdAdmin.Application\FirebirdAdmin.Application.csproj" />
    <ProjectReference Include="..\FirebirdAdmin.Domain\FirebirdAdmin.Domain.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
</Project>
